[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cms = [
  'cd ../..',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cms = [
  'cd ../..',
  'pnpm --filter web build'
]

[start]
cmd = 'cd ../../apps/web && pnpm start'.